services:
  backend:
    image: ghcr.io/janderjanderjanderjander/restaurant-reservation-backend:latest
    ports:
      - "8082:8080"

  frontend:
    image: ghcr.io/janderjanderjanderjander/restaurant-reservation-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
